# Generated by Django 2.1.7 on 2019-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignemntSimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('proscons', models.TextField()),
                ('example', models.TextField()),
            ],
        ),
    ]
